package hotelbeds_v3;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

import javax.net.ssl.HttpsURLConnection;

public class Availability {

	public static void main(String[] args) {
		try {
			// Your API Key and secret
			String apiKey = "qh7javyaw8wjfcfeqfj2wf79";
			String Secret = "DzkPcKJRu2"; 
			// Signature is generated by SHA256 (Api-Key + Secret +
			// Timestamp (in seconds))
			// String signature = org.apache.commons.codec.digest.DigestUtils.sha256Hex(apiKey + Secret + System.currentTimeMillis() / 1000);

			String signature = hash256(apiKey + Secret + System.currentTimeMillis() / 1000);

			// Example of call to the API
			String endpoint = "https://api.test.hotelbeds.com/hotel-api/1.0/status";
			URL url = new URL(endpoint);

			HttpsURLConnection connection = (HttpsURLConnection) url.openConnection();
			connection.setRequestProperty("X-Signature", signature);
			connection.setRequestProperty("Api-Key", apiKey);
			connection.setRequestProperty("Accept", "application/json");

			InputStream ins = connection.getInputStream();
			InputStreamReader isr = new InputStreamReader(ins);
			BufferedReader in = new BufferedReader(isr);

			String inputLine;
			while ((inputLine = in.readLine()) != null) {
				System.out.println(inputLine);
			}
			in.close();
		} catch (Exception e) {
			e.printStackTrace();
		}

	}

	public static String hash256(String data) throws NoSuchAlgorithmException {
		MessageDigest md = MessageDigest.getInstance("SHA-256");
		md.update(data.getBytes());
		return bytesToHex(md.digest());
	}

	public static String bytesToHex(byte[] bytes) {
		StringBuffer result = new StringBuffer();
		for (byte byt : bytes)
			result.append(Integer.toString((byt & 0xff) + 0x100, 16).substring(1));
		return result.toString();
	}

}
